apiVersion: v1
kind: Pod
metadata:
  name: nodeapp1
  labels:
    app: nodeapp1
spec:
  containers:
    - name: nodeapp1
      image: kayeofhallownest/nodeapp1:tagVersion
      ports:
        - containerPort: 5000
