apiVersion: v2
kind: Pod
metadata:
  name: nodeapp1
  labels:
    app: nodeapp1
spec:
  containers:
    - name: nodeapp
      image: kayeofhallownest/nodeapp1:tagVersion
      ports:
        - containerPort: 30000
